# Generated by Django 5.0.6 on 2025-06-16 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('bbox', models.JSONField(verbose_name='Координаты (x,y,w,h)')),
                ('times', models.JSONField(default=list, verbose_name='История занятости')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
                'ordering': ['created_at'],
            },
        ),
    ]
